In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as mlp

In [11]:
df_products = pd.read_csv("C:/Users/Mohan/Documents/Candy/data/version_0/Candy_Products.csv")

In [12]:
df_products.head()

,Division,Product Name,Factory,Product ID,Unit Price,Unit Cost
0,Chocolate,Wonka Bar - Nutty Crunch Surprise,Lot's O' Nuts,CHO-NUT-13000,3.49,1.00
1,Chocolate,Wonka Bar - Fudge Mallows,Lot's O' Nuts,CHO-FUD-51000,3.60,1.20
2,Chocolate,Wonka Bar -Scrumdiddlyumptious,Lot's O' Nuts,CHO-SCR-58000,3.60,1.10
3,Chocolate,Wonka Bar - Milk Chocolate,Wicked Choccy's,CHO-MIL-31000,3.25,1.14
4,Chocolate,Wonka Bar - Triple Dazzle Caramel,Wicked Choccy's,CHO-TRI-54000,3.75,1.30

In [13]:
df_products.shape

(15, 6)

In [14]:
df_products.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Division      15 non-null     str
 1   Product Name  15 non-null     str
 2   Factory       15 non-null     str
 3   Product ID    15 non-null     str
 4   Unit Price    15 non-null     float64
 5   Unit Cost     15 non-null     float64
dtypes: float64(2), str(4)
memory usage: 852.0 bytes

In [15]:
df_products.describe()

       Unit Price  Unit Cost
count   15.000000  15.000000
mean     4.462000   1.806000
std      4.790102   2.344866
min      1.250000   0.600000
25%      1.745000   0.850000
50%      3.490000   1.100000
75%      3.750000   1.400000
max     20.000000  10.000000

In [16]:
df_products.isnull().sum()

Division        0
Product Name    0
Factory         0
Product ID      0
Unit Price      0
Unit Cost       0
dtype: int64

In [17]:
df_products.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
dtype: bool

In [18]:

# Save CSV
df_products.to_csv("C:/Users/Mohan/Documents/Candy/data/version_1/Candy_Products.csv", index=False)