In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df_targets = pd.read_csv("C:/Users/Mohan/Documents/Candy/data/version_0/Candy_Targets.csv")

In [4]:
df_targets.head()

    Division  Target
0  Chocolate   27000
1      Sugar   15000
2      Other    3000

In [5]:
df_targets.shape

(3, 2)

In [6]:
df_targets.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Division  3 non-null      str
 1   Target    3 non-null      int64
dtypes: int64(1), str(1)
memory usage: 180.0 bytes

In [7]:
df_targets.describe()

        Target
count      3.0
mean   15000.0
std    12000.0
min     3000.0
25%     9000.0
50%    15000.0
75%    21000.0
max    27000.0

In [8]:
df_targets["Division"] = df_targets["Division"].astype("string")

In [9]:
print(df_targets["Division"].dtype)

string

In [10]:
df_targets.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Division  3 non-null      string
 1   Target    3 non-null      int64
dtypes: int64(1), string(1)
memory usage: 180.0 bytes

In [11]:
df_targets.isnull().sum()

Division    0
Target      0
dtype: int64

In [12]:
df_targets.duplicated()

0    False
1    False
2    False
dtype: bool

In [13]:
df_targets.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Division  3 non-null      string
 1   Target    3 non-null      int64
dtypes: int64(1), string(1)
memory usage: 180.0 bytes

In [14]:
# Save CSV
df_targets.to_csv("C:/Users/Mohan/Documents/Candy/data/version_1/Candy_Targets.csv", index=False)